const subjects = [
  ["History & Society", ["Briefly discuss the Divide and Rule policy of 1947.", "Describe all types of discrimination to East Pakistan during the Pakistan regime.", "Discuss the role of the Language Movement for flourishing Bengali Nationalism.", "How can the Bengali language be promoted and effectively used at all levels of society? Suggest practical guidelines.", "Describe the Education Movement in 1962 (17 September).", "Describe the role of students and women in Liberation War.", "In which sectors did the Z-Force conduct its operations during the Liberation War?", "Write the role of Z-Force in the overall success of the Liberation War.", "The Liberation War was not organized under a single leadership; it was a people's war - explain.", "Write the importance of Maulana Abdul Hamid Khan Bhashani in the political history of Bengal.", "Discuss the role of foreign countries during the Liberation War (USA, China, India, USSR, UK, France and UN)."]],
  ["Geography & Resources", ["Discuss briefly the natural resources of Bangladesh.", "Discuss the configuration of land/physiographic units, human habitation, area and location of Bangladesh.", "Briefly discuss the geography of Bangladesh.", "What is Blue Economy? How can Bangladesh benefit from Blue Economy?", "Discuss the causes of climate change/reasons of environmental degradation/effects in Bangladesh.", "Make a relationship between environment and development.", "Define Demographic Dividend. Discuss the challenges and opportunities of Demographic Dividend in Bangladesh.", "What is Demographic Winter and how can Bangladesh benefit from a Demographic Winter situation?", "Discuss the challenges and opportunities for the geographical location of Bangladesh.", "Mention the sources of natural gas and coal in Bangladesh and describe the role of gas and coal in economic development."]],
  ["Social Structure & Culture", ["Describe the cultural heritage of Bangladesh (Sundarban, Shat Gombuj Mosque, Buddhist Bihar etc.).", "Describe the ethnic and cultural diversity in Bangladesh.", "Explain the importance of communal harmony for the development of Bangladesh.", "Write short notes: Ekushey Book Fair, Bengali New Year, Geographical Indication (GI) Products."]],
  ["Politics & Constitution", ["Define constitution. Discuss the different types of constitution.", "Mention the main characteristics of the constitution of Bangladesh.", "Differentiate between human rights and fundamental rights.", "Mention main fundamental rights of Bangladesh constitution. What obstacles do citizens face in ensuring fundamental rights?", "Analyze the constitutional amendments and their impact on democracy in Bangladesh.", "What is your vision for building Bangladesh in the spirit of the July Revolution?", "Describe the three organs of the state of Bangladesh/structure of government of Bangladesh.", "Write the importance of free and fair election for a democratic country.", "Describe advantages and disadvantages of democracy in Bangladesh.", "Define Civil Society. Write the role of Civil Society in national development.", "Briefly discuss the role of youth in building the New Bangladesh.", "Describe the role of Gen-Z in the July revolution 2024."]],
  ["Economy", ["Explain GDP, GNP, Per Capita Income, NNP.", "Write down the challenges and opportunities after the graduation from LDC for Bangladesh.", "Describe the importance of foreign remittance and FDI. What steps are needed to increase FDI and remittance?", "What is economic development? Describe the characteristics of the economy of Bangladesh. Write the obstacles to economic development.", "What is money laundering? What measures should be taken to combat this problem?", "Write down the success of present Government in economic diplomacy."]],
  ["Achievements", ["Briefly discuss some glorious achievements in different sectors of Bangladesh.", "Discuss women empowerment of Bangladesh.", "What is sustainable development? Why is it crucial for a developing country like Bangladesh?", "Write the differences between MDGs and SDGs.", "Describe the three zero theory.", "What is 4IR? Write the challenges of the 4IR in the context of Bangladesh.", "How does 5IR differ from 4IR? Write the positive and negative impact of 5IR."]],
  ["Socio-Cultural Problems", ["Write down the social problems of Bangladesh (please see PDF sheet).", "Describe the unemployment problem of Bangladesh. What kind of educational reform should be taken to reduce the problem?"]]
];
const baseQuestions = subjects.flatMap(([subject, items]) => items.map((text, index) => ({ id: `${subject}-${index + 1}`, subject, text, source: "Suggestions for Final Examination", original: true })));
const storageKey = "question-tracker-v2";
const legacy = JSON.parse(localStorage.getItem("question-tracker-v1") || "{}");
const saved = JSON.parse(localStorage.getItem(storageKey) || "{}");
const state = { solved: saved.solved || legacy.solved || {}, examDate: saved.examDate || legacy.examDate || "", metadata: saved.metadata || {}, additions: saved.additions || [] };
const list = document.querySelector("#questionList"), template = document.querySelector("#questionTemplate");
const subjectFilter = document.querySelector("#subjectFilter"), statusFilter = document.querySelector("#statusFilter"), importantFilter = document.querySelector("#importantFilter"), searchInput = document.querySelector("#searchInput"), examDate = document.querySelector("#examDate");
function allQuestions() { return [...baseQuestions, ...state.additions]; }
function meta(id) { return state.metadata[id] || { rating: 0, priority: "Normal", chapter: "", tags: "", notes: "", important: false, bookmarked: false, revision: false }; }
function setMeta(id, patch) { state.metadata[id] = { ...meta(id), ...patch }; }
function sourceFor(question) { return meta(question.id).sources || question.source || "Manual"; }
function persist() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function refreshSubjects() { const chosen = subjectFilter.value; subjectFilter.replaceChildren(new Option("All subjects", "all")); [...new Set(allQuestions().map(q => q.subject))].sort().forEach(subject => subjectFilter.add(new Option(subject, subject))); subjectFilter.value = [...subjectFilter.options].some(o => o.value === chosen) ? chosen : "all"; }
function normalized(text) { return text.toLowerCase().replace(/[^a-z0-9\s]/g, "").replace(/\s+/g, " ").trim(); }
function render() { const search = searchInput.value.trim().toLowerCase(), subject = subjectFilter.value, status = statusFilter.value, focus = importantFilter.value, questions = allQuestions(); const filtered = questions.filter(q => { const m = meta(q.id), solved = Boolean(state.solved[q.id]); const statusOK = status === "all" || (status === "solved" && solved) || (status === "unsolved" && !solved) || (status === "revision" && m.revision); const focusOK = focus === "all" || (focus === "important" && m.important) || (focus === "bookmarked" && m.bookmarked) || (focus === "five-star" && Number(m.rating) === 5) || (focus === "quick-study" && m.important && !solved); return (subject === "all" || q.subject === subject) && statusOK && focusOK && `${q.text} ${q.subject} ${m.chapter} ${m.tags} ${sourceFor(q)}`.toLowerCase().includes(search); }); list.replaceChildren(); filtered.forEach(question => renderQuestion(question)); document.querySelector("#resultCount").textContent = `Showing ${filtered.length} of ${questions.length} questions`; document.querySelector("#emptyState").hidden = filtered.length > 0; }
function renderQuestion(question) { const m = meta(question.id), node = template.content.cloneNode(true), card = node.querySelector(".question-card"); const solved = node.querySelector(".solved-toggle"); solved.checked = Boolean(state.solved[question.id]); solved.setAttribute("aria-label", `Mark question ${question.id} as solved`); solved.addEventListener("change", () => { state.solved[question.id] = solved.checked; persist(); updateDashboard(); render(); }); node.querySelector(".question-text").textContent = question.text; node.querySelector(".subject-tag").textContent = question.subject; const chapter = node.querySelector(".chapter-tag"); chapter.textContent = m.chapter || "No chapter"; const source = node.querySelector(".source-tag"); source.textContent = sourceFor(question); const important = node.querySelector(".important-button"); important.textContent = m.important ? "★" : "☆"; important.classList.toggle("active", m.important); important.addEventListener("click", () => { setMeta(question.id, { important: !m.important }); persist(); updateDashboard(); render(); }); const bookmark = node.querySelector(".bookmark-button"); bookmark.classList.toggle("active", m.bookmarked); bookmark.addEventListener("click", () => { setMeta(question.id, { bookmarked: !m.bookmarked }); persist(); updateDashboard(); render(); }); const details = node.querySelector(".question-details"); node.querySelector(".details-button").addEventListener("click", () => { details.hidden = !details.hidden; }); const rating = node.querySelector(".rating-select"), priority = node.querySelector(".priority-select"), chapterInput = node.querySelector(".chapter-input"), tags = node.querySelector(".tags-input"), notes = node.querySelector(".notes-input"), revision = node.querySelector(".revision-toggle"); rating.value = m.rating; priority.value = m.priority; chapterInput.value = m.chapter; tags.value = m.tags; notes.value = m.notes; revision.checked = m.revision; node.querySelector(".save-details").addEventListener("click", () => { setMeta(question.id, { rating: Number(rating.value), priority: priority.value, chapter: chapterInput.value.trim(), tags: tags.value.trim(), notes: notes.value, revision: revision.checked }); persist(); updateDashboard(); render(); }); node.querySelector(".edit-button").addEventListener("click", () => openQuestionDialog(question)); const deleteButton = node.querySelector(".delete-button"); if (question.original) { deleteButton.hidden = true; } else { deleteButton.addEventListener("click", () => { if (confirm("Delete this manually added question? This cannot be undone.")) { state.additions = state.additions.filter(q => q.id !== question.id); delete state.metadata[question.id]; delete state.solved[question.id]; persist(); refreshSubjects(); updateDashboard(); render(); } }); } list.append(card); }
function updateDashboard() { const questions = allQuestions(), solved = questions.filter(q => state.solved[q.id]).length, important = questions.filter(q => meta(q.id).important), solvedImportant = important.filter(q => state.solved[q.id]).length, percent = questions.length ? Math.round((solved / questions.length) * 100) : 0; document.querySelector("#completionPercentage").textContent = `${percent}%`; document.querySelector("#progressBar").style.width = `${percent}%`; document.querySelector("#progressSummary").textContent = `${solved} of ${questions.length} questions solved`; document.querySelector("#remainingCount").textContent = questions.length - solved; document.querySelector("#importantSummary").textContent = `${important.length} important · ${solvedImportant}/${important.length || 0} solved`; updateCountdown(); }
function updateCountdown() { const target = state.examDate ? new Date(`${state.examDate}T00:00:00`) : null; const output = document.querySelector("#countdown"); if (!target || Number.isNaN(target)) { output.textContent = "Set a date"; return; } const days = Math.ceil((target - new Date()) / 86400000); output.textContent = days < 0 ? "Exam passed" : days === 0 ? "Today!" : `${days} day${days === 1 ? "" : "s"} left`; }
const dialog = document.querySelector("#questionDialog"), form = document.querySelector("#questionForm"), duplicateNotice = document.querySelector("#duplicateNotice");
function openQuestionDialog(question) { form.reset(); duplicateNotice.hidden = true; document.querySelector("#dialogTitle").textContent = question ? "Edit question" : "Add question"; document.querySelector("#editingId").value = question?.id || ""; document.querySelector("#questionText").value = question?.text || ""; document.querySelector("#questionSubject").value = question?.subject || ""; document.querySelector("#questionChapter").value = question ? meta(question.id).chapter : ""; document.querySelector("#questionSource").value = question ? sourceFor(question) : ""; dialog.showModal(); }
document.querySelector("#addButton").addEventListener("click", () => openQuestionDialog()); document.querySelector("#closeDialog").addEventListener("click", () => dialog.close());
form.addEventListener("submit", event => { event.preventDefault(); const id = document.querySelector("#editingId").value, text = document.querySelector("#questionText").value.trim(), subject = document.querySelector("#questionSubject").value.trim(), chapter = document.querySelector("#questionChapter").value.trim(), source = document.querySelector("#questionSource").value.trim() || "Manual entry"; const exact = allQuestions().find(q => q.id !== id && normalized(q.text) === normalized(text)); if (exact && !id) { setMeta(exact.id, { sources: [...new Set(sourceFor(exact).split(" · ").concat(source))].join(" · "), chapter: meta(exact.id).chapter || chapter }); persist(); dialog.close(); updateDashboard(); render(); return; } if (id) { const target = state.additions.find(q => q.id === id) || baseQuestions.find(q => q.id === id); Object.assign(target, { text, subject, source }); setMeta(id, { chapter, sources: source }); } else { const question = { id: `manual-${Date.now()}`, text, subject, source, original: false }; state.additions.push(question); setMeta(question.id, { chapter }); } persist(); refreshSubjects(); dialog.close(); updateDashboard(); render(); });
document.querySelector("#questionText").addEventListener("input", event => { const match = allQuestions().find(q => normalized(q.text) === normalized(event.target.value)); duplicateNotice.hidden = !match; duplicateNotice.textContent = match ? `Exact duplicate found: “${match.text}”. Saving will merge this source with the existing question.` : ""; });
[searchInput, subjectFilter, statusFilter, importantFilter].forEach(control => control.addEventListener("input", render)); examDate.value = state.examDate; examDate.addEventListener("change", () => { state.examDate = examDate.value; persist(); updateCountdown(); }); document.querySelector("#resetButton").addEventListener("click", () => { if (confirm("Clear solved progress and the exam date? Your questions and notes are kept.")) { state.solved = {}; state.examDate = ""; examDate.value = ""; persist(); updateDashboard(); render(); } });
refreshSubjects(); updateDashboard(); render();
